version: "3.8"

services:
  backend:
    build: ./backend
    container_name: password_backend
    ports:
      - "8001:8000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      - PORT=8000
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis
    entrypoint: ["deno", "run", "-A", "main.ts"]

    networks:
      - nginx-config_docker_shared_network

  redis:
    image: redis:7-alpine
    container_name: password_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - nginx-config_docker_shared_network

volumes:
  redis_data:

networks:
  nginx-config_docker_shared_network:
    external: true
